/**
 * notificationConstants.js
 * Created by Emre KACAN(emrekacan@gmail.com)
 * on 27/02/2018.
 */

exports.NOTIFICATIONS_CONSTANTS = {
    "en": [
        "is interested",
        "Match request accepted",
        "Asked to be friends",
        "Friend request accepted",
        "Invites you to join on here activity",
        "invitation request accepted",
        "Would be interested in joining next time",
        "Want to join your scheduled activity",
        "Accepted join request",
        "Likes to join",
        "Accepted meet request",
        "Wants to be your friends and join",
        "Join and friend request accepted",
        "Canceled the event",
        "Asked your phone number",
        "Accepted phone number request",
        "Asked your email address",
        "Accepted email address request",
        "Event is cancelled or no longer available",
        "The activity is started or already happened",
        "Commented to own post",
        "Commented on your post"
    ],
    "de": [
        "Hat eine Matchanfrage gesendet",
        "Es ist ein Match",
        "Hat eine Freundschaftsanfrage geschickt",
        "Akzeptiert Freundschaftsanfrage",
        "Lädt ein, an der folgenden Aktivität teilzunehmen",
        "Einladung annehmen",
        "Nächstes Mal",
        "Möchte an geplanten Aktivität teilnehmen",
        "Macht mit deiner Aktivität mit",
        "Möchte an geplanten Aktivität teilnehmen",
        "Einladung annehmen",
        "Möchte an geplanten Aktivität teilnehmen",
        "Macht mit deiner Aktivität mit",
        "Die folgende Aktivität wurde abgebrochen",
        "Hat deine Telefonnummer angefragt",
        "Telefonnummer Anfrage akzeptiert",
        "Hat eine Mailanfrage gesendet",
        "Akzeptiert Mail-Anfrage",
        "Aktivität ist nicht mehr verfügbar",
        "Aktivität wurde abgebrochen oder hat bereits stattgefunden",
        "Hat auf own Nachricht reagiert",
        "Hat auf Ihre Nachricht reagiert"
    ],
    "fr":
        [
            "A envoyé une demande de match",
            "C'est un match",
            "A vous envoyer une demande d'ami",
            "Accepte votre demande d'ami",
            "Vous invite joindre à l'activité suivante",
            "Accepter l'invitation",
            "La prochaine fois",
            "Souhaite se joindre à l'activité prévue",
            "Inscrit à votre activité",
            "Souhaite se joindre à l'activité prévue",
            "Accepter l'invitation",
            "Souhaite se joindre à l'activité prévue",
            "Inscrit à votre activité",
            "Annulé l'activité suivante",
            "Demande de votre numéro de téléphone",
            "Demande de numéro de téléphone acceptée",
            "A envoyé une demande de e-mail",
            "Accepté demande de e-mail",
            "Activité n'est plus disponible",
            "L'activité a été annulée ou a déjà eu lieu",
            "A commenté à son own poste",
            "A commenté votre message"
        ],
    "nl": [
        "Heeft jou een match verzoek gestuurd",
        "Het is een match",
        "Heeft jouw een vriendschapsverzoek gestuurd",
        "Heeft jouw vriendschapsverzoek geacepteerd",
        "Nodigt je uit voor de volgende activiteit",
        "Uitnodiging geaccepteerd",
        "Volgende keer",
        "Wil mee doen met jouw geplande activiteit",
        "Neemt deel aan jouw activiteit",
        "Wil mee doen met jouw geplande activiteit",
        "Uitnodiging geaccepteerd",
        "Wil mee doen met jouw geplande activiteit",
        "Neemt deel aan jouw activiteit",
        "Heeft de volgende activiteit afgezegd",
        "Heeft jou een telefoonnummer verzoek gestuurd",
        "Telefoonnummer verzoek geaccepteerd",
        "Heeft jou een een mail verzoek gestuurd",
        "Heeft jou mail verzoek geaccepteerd",
        "Activiteit is niet langer beschikbaar",
        "De activiteit is al gestart of heeft al plaatsgevonden",
        "Gereageerd op own bericht",
        "Heeft gereageerd op je bericht"
    ],
    "tr":
        [
            "Sana bir beğeni isteği gönderdi",
            "Beğendin",
            "Sana bir arkadaşlık isteği gönderdi",
            "Arkadaşlık isteğini kabul etti",
            "Sizi bu etkinliğe katılmaya davet ediyor",
            "Davetini kabul etti",
            "Bir daha ki sefere katılmak istedi",
            "Planladığınız etkinliğe katılmak istiyor",
            "Etkinliğine katıldı",
            "Planladığınız etkinliğe katılmak istiyor",
            "Etkinliğine katıldı",
            "Arkadaşın olmak ve etkinliğine katılmak istiyor",
            "Etkinliğine katıldı",
            "Bu etkinlik iptal edildi",
            "Sana bir telefon numarası isteği gönderdi",
            "Telefon numarası isteği kabul edildi",
            "Sana bir e-posta isteği gönderdi",
            "E-posta isteği kabul edildi",
            "Etkinlik iptal edildi veya artık mevcut değil",
            "Etkinliğe katılmayı kaçırdı",
        ]
};